kennel/config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from .views import clear_modal

urlpatterns = (
    [
        path("admin/", admin.site.urls),
        path("clear-modal/", clear_modal, name="clear_modal"),
        path("", include("dogs.urls", namespace="dogs")),
        path("users/", include("users.urls", namespace="users")),
    ]
    + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
)

kennel/dogs/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from .apps import DogsConfig
from . import views

app_name = DogsConfig.name

urlpatterns = [
    path(
        "",
        cache_page(600)(views.index),
        name="index",
    ),
    path(
        "breeds/",
        views.BreedList.as_view(),
        name="breeds",
    ),
    path(
        "breeds/<int:breed_id>/dogs/",
        views.DogsByBreed.as_view(),
        name="dogs_by_breed",
    ),
    path(
        "dogs/",
        views.DogListView.as_view(),
        name="dogs_list",
    ),
    path(
        "dogs/create/",
        views.DogCreateView.as_view(),
        name="dog_create",
    ),
    path(
        "dogs/detail/<int:pk>/",
        views.DogDetailView.as_view(),
        name="dog_detail",
    ),
    path(
        "dogs/update/<int:pk>/",
        views.DogUpdateView.as_view(),
        name="dog_update",
    ),
    path(
        "dogs/delete/<int:pk>/",
        views.DogDeleteView.as_view(),
        name="dog_delete",
    ),
    path(
        "dogs/delete/confirm/<int:pk>/",
        views.DogDeleteConfirmView.as_view(),
        name="dog_delete_confirm",
    ),
    path(
        "dogs/delete/abort/<int:pk>/",
        views.DogDeleteAbort.as_view(),
        name="dog_delete_abort",
    ),
]

kennel/users/urls.py
from django.urls import path

from .apps import UsersConfig
from . import views


app_name = UsersConfig.name


urlpatterns = [
    path(
        "",
        views.UserLoginView.as_view(),
        name="login",
    ),
    path(
        "register/",
        views.UserRegisterViews.as_view(),
        name="register",
    ),
    path(
        "profile/",
        views.UserProfileView.as_view(),
        name="profile",
    ),
    path(
        "profile/update/",
        views.UserUpdateView.as_view(),
        name="update",
    ),
    path(
        "profile/password-change/",
        views.UserPasswordChangeView.as_view(),
        name="password-change",
    ),
    path(
        "reset-password/",
        views.UserResetPasswordView.as_view(),
        name="reset-password",
    ),
    path(
        "reset-password-success/",
        views.reset_password_success,
        name="reset-password-success",
    ),
    path(
        "logout/",
        views.UserLogoutView.as_view(),
        name="logout",
    ),
]

kennel/config/core/templates/includes/footer.html
{% load static %}
<footer class="footer">
  <div class="container">
    {#    <nav class="footer__menu">#}
    {#      <ul class="footer__menu-list">#}
    {#        <li class="footer__menu-item">#}
    {#          <p href="#" class="footer__menu-title">Пример 1</p>#}
    {#        </li>#}
    {#        <li class="footer__menu-item"><a href="#" class="footer__menu-link">Ссылка 1</a></li>#}
    {#        <li class="footer__menu-item"><a href="#" class="footer__menu-link">Ссылка 2</a></li>#}
    {#        <li class="footer__menu-item"><a href="#" class="footer__menu-link">Ссылка 3</a></li>#}
    {#      </ul>#}
    {#      <ul class="footer__menu-list">#}
    {#        <li class="footer__menu-item">#}
    {#          <p href="#" class="footer__menu-title">Пример 2</p>#}
    {#        </li>#}
    {#        <li class="footer__menu-item"><a href="#" class="footer__menu-link">Ссылка 1</a></li>#}
    {#        <li class="footer__menu-item"><a href="#" class="footer__menu-link">Ссылка 2</a></li>#}
    {#        <li class="footer__menu-item"><a href="#" class="footer__menu-link">Ссылка 3</a></li>#}
    {#      </ul>#}
    {#      <ul class="footer__menu-list">#}
    {#        <li class="footer__menu-item">#}
    {#          <p href="#" class="footer__menu-title">Пример 3</p>#}
    {#        </li>#}
    {#        <li class="footer__menu-item"><a href="#" class="footer__menu-link">Ссылка 1</a></li>#}
    {#        <li class="footer__menu-item"><a href="#" class="footer__menu-link">Ссылка 2</a></li>#}
    {#        <li class="footer__menu-item"><a href="#" class="footer__menu-link">Ссылка 3</a></li>#}
    {#      </ul>#}
    {#      <ul class="footer__menu-list">#}
    {#        <li class="footer__menu-item">#}
    {#          <p href="#" class="footer__menu-title">Пример 4</p>#}
    {#        </li>#}
    {#        <li class="footer__menu-item"><a href="#" class="footer__menu-link">Ссылка 1</a></li>#}
    {#        <li class="footer__menu-item"><a href="#" class="footer__menu-link">Ссылка 2</a></li>#}
    {#        <li class="footer__menu-item"><a href="#" class="footer__menu-link">Ссылка 3</a></li>#}
    {#      </ul>#}
    {#    </nav>#}
    <ul class="app">
      <li class="app__item">
        <a href="#" class="app__item-link">
          <img class="app__item-img" src="{% static 'images/icons/appstore.svg' %}" alt=""/>
        </a>
      </li>
      <li class="app__item">
        <a href="https://github.com/COD-e-x/django-academy-web" class="app__item-link" target="_blank">
          <img class="app__item-img" src="{% static 'images/icons/github.svg' %}" alt=""/>
        </a>
      </li>
      <li class="app__item">
        <a href="#" class="app__item-link">
          <img class="app__item-img" src="{% static 'images/icons/googleplay.svg' %}" alt=""/>
        </a>
      </li>
    </ul>
    <div class="footer__copy">
      <p class="footer__copy-text">
        Если у вас есть вопросы о наших услугах или услугах питомника, пожалуйста, позвоните по телефону:
        <br>8-999-888-7777. Все партнеры питомника обязаны соблюдать высокие стандарты ухода за животными и пройти
        программу
        сертификации.
      </p>
    </div>
    <nav class="copy__nav">
      <ul class="copy__nav-list">
        <li>
          <copy__nav-item><a href="#" class="copy__nav-link">Terms of Service</a></copy__nav-item>
        </li>
        <li>
          <copy__nav-item><a href="#" class="copy__nav-link">Privacy Policy</a></copy__nav-item>
        </li>
        <li>
          <copy__nav-item
          ><a href="#" class="copy__nav-link">Do Not Sell My Personal Information</a></copy__nav-item
          >
        </li>
      </ul>
    </nav>
  </div>
</footer>

kennel/config/core/templates/includes/header.html
{% load static %}
<header class="header">
  <div class="container">
    <div class="header__content">
      <a class="header__logo logo" href="{% url 'dogs:index' %}">
        <img class="logo__image" src="{% static 'images/logo.svg' %}" alt="logo">
      </a>
      <button class="header__menu-toggle" aria-label="Menu">
        <span></span>
        <span></span>
        <span></span>
      </button>
      <nav class="header__nav">
        <ul class="header__menu-list--text header__menu-list">
          <li class="header__menu-item">
            <a class="header__menu-link {% if request.path == '/' %}header__menu-link--active{% endif %}"
               href="{% url 'dogs:index' %}">Главная</a>
          </li>
          <li class="header__menu-item">
            <a class="header__menu-link {% if request.path == '/breeds/' %}header__menu-link--active{% endif %}"
               href="{% url 'dogs:breeds' %}">Породы</a>
          </li>
          <li class="header__menu-item">
            <a class="header__menu-link {% if request.path == '/dogs/' %}header__menu-link--active{% endif %}"
               href="{% url 'dogs:dogs_list' %}">Собаки</a>
          </li>
        </ul>
        <div class="header__user-info">
          {% if user.is_authenticated %}
            <div class="header__user-info--auth">
              <a class="header__menu-link" href="{% url 'users:profile' %}">
                <small class="header__icon-email">
                  {{ user.email }}
                </small></a>
            </div>
          {% endif %}
          <ul class="header__menu-list--icon header__menu-list">
            {% if user.is_authenticated %}
              {% if user.is_superuser %}
                <li class="header__menu-item">
                  <a class="header__icon--admin header__icon" href="/admin/">
                    <img class="header__icon-image" src="{% static 'images/icons/admin.svg' %}" alt="admin">
                  </a>
                </li>
              {% endif %}
              <li class="header__menu-item">
                <a class="header__icon--dog-add header__icon" href="{% url 'dogs:dog_create' %}">
                  <img class="header__icon-image" src="{% static 'images/icons/dog-add.svg' %}" alt="dog add">
                </a>
              </li>
              <li class="header__menu-item">
                <form method="post" action="{% url "users:logout" %}">
                  {% csrf_token %}
                  <button type="submit" class="header__icon header__icon--logout"
                          style="background: none; border: none; padding: 0;">
                    <img class="header__icon-image" src="{% static 'images/icons/logout.svg' %}" alt="logout">
                  </button>
                </form>
              </li>
            {% else %}
              <li class="header__menu-item">
                <a class="header__icon--user-add header__icon" href="{% url 'users:register' %}">
                  <img class="header__icon-image" src="{% static 'images/icons/user-add.svg' %}" alt="user add">
                </a>
              </li>
              <li class="header__menu-item">
                <a class="header__icon--login header__icon" href="{% url 'users:login' %}">
                  <img class="header__icon-image" src="{% static 'images/icons/login.svg' %}" alt="login">
                </a>
              </li>
            {% endif %}
          </ul>
        </div>
      </nav>
    </div>
  </div>
</header>


{% block scripts %}
  <script>
      document.addEventListener('DOMContentLoaded', function () {
          const menuToggle = document.querySelector('.header__menu-toggle');
          const nav = document.querySelector('.header__nav');
          const header = document.querySelector('.header');

          function closeMenu() {
              menuToggle.classList.remove('active');
              nav.classList.remove('active');
              document.body.classList.remove('no-scroll');
              menuToggle.setAttribute('aria-expanded', 'false');
          }

          menuToggle.addEventListener('click', function (e) {
              e.stopPropagation();
              const isOpen = this.classList.contains('active');

              if (isOpen) {
                  closeMenu();
              } else {
                  this.classList.add('active');
                  nav.classList.add('active');
                  document.body.classList.add('no-scroll');
                  this.setAttribute('aria-expanded', 'true');
              }
          });
          document.addEventListener('click', function (e) {
              if (!header.contains(e.target) && nav.classList.contains('active')) {
                  closeMenu();
              }
          });
          window.addEventListener('scroll', function () {
              if (nav.classList.contains('active')) {
                  closeMenu();
              }
          });
          window.addEventListener('resize', function () {
              if (window.innerWidth > 992 && nav.classList.contains('active')) {
                  closeMenu();
              }
          });
      });
  </script>
{% endblock %}

kennel/config/core/templates/includes/title-top.html
<div class="title--top">
  {{ title }}
</div>