kennel/config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from .views import clear_modal

urlpatterns = (
    [
        path("admin/", admin.site.urls),
        path("clear-modal/", clear_modal, name="clear_modal"),
        path("", include("dogs.urls", namespace="dogs")),
        path("users/", include("users.urls", namespace="users")),
    ]
    + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
)

kennel/dogs/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from .apps import DogsConfig
from . import views

app_name = DogsConfig.name

urlpatterns = [
    path(
        "",
        cache_page(600)(views.index),
        name="index",
    ),
    path(
        "breeds/",
        views.BreedList.as_view(),
        name="breeds",
    ),
    path(
        "breeds/<int:breed_id>/dogs/",
        views.DogsByBreed.as_view(),
        name="dogs_by_breed",
    ),
    path(
        "dogs/",
        views.DogListView.as_view(),
        name="dogs_list",
    ),
    path(
        "dogs/create/",
        views.DogCreateView.as_view(),
        name="dog_create",
    ),
    path(
        "dogs/detail/<int:pk>/",
        views.DogDetailView.as_view(),
        name="dog_detail",
    ),
    path(
        "dogs/update/<int:pk>/",
        views.DogUpdateView.as_view(),
        name="dog_update",
    ),
    path(
        "dogs/delete/<int:pk>/",
        views.DogDeleteView.as_view(),
        name="dog_delete",
    ),
    path(
        "dogs/delete/confirm/<int:pk>/",
        views.DogDeleteConfirmView.as_view(),
        name="dog_delete_confirm",
    ),
    path(
        "dogs/delete/abort/<int:pk>/",
        views.DogDeleteAbort.as_view(),
        name="dog_delete_abort",
    ),
]

kennel/users/urls.py
from django.urls import path

from .apps import UsersConfig
from . import views


app_name = UsersConfig.name


urlpatterns = [
    path(
        "",
        views.UserLoginView.as_view(),
        name="login",
    ),
    path(
        "register/",
        views.UserRegisterViews.as_view(),
        name="register",
    ),
    path(
        "profile/",
        views.UserProfileView.as_view(),
        name="profile",
    ),
    path(
        "profile/update/",
        views.UserUpdateView.as_view(),
        name="update",
    ),
    path(
        "profile/password-change/",
        views.UserPasswordChangeView.as_view(),
        name="password-change",
    ),
    path(
        "reset-password/",
        views.UserResetPasswordView.as_view(),
        name="reset-password",
    ),
    path(
        "reset-password-success/",
        views.reset_password_success,
        name="reset-password-success",
    ),
    path(
        "logout/",
        views.UserLogoutView.as_view(),
        name="logout",
    ),
]

kennel/users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

NULLABLE = {"null": True, "blank": True}
NULLABLE_FOR_STRING = {"null": False, "blank": True}


class UserRole(models.TextChoices):
    ADMIN = "admin", "Администратор"
    MODERATOR = "moderator", "Модератор"
    USER = "user", "Пользователь"


class User(AbstractUser):
    """Модель для пользователя."""

    username = None
    first_name = models.CharField(
        max_length=30,
        **NULLABLE_FOR_STRING,
        verbose_name="Имя",
    )
    last_name = models.CharField(
        max_length=30,
        **NULLABLE_FOR_STRING,
        verbose_name="Фамилия",
    )
    email = models.EmailField(
        unique=True,
        verbose_name="Эл. почта",
    )
    phone = models.CharField(
        max_length=35,
        verbose_name="Номер телефона",
        **NULLABLE_FOR_STRING,
    )
    telegram = models.CharField(
        max_length=50,
        verbose_name="Телеграм",
        **NULLABLE_FOR_STRING,
    )
    birth_date = models.DateField(
        **NULLABLE,
        verbose_name="Дата рождения",
    )
    gender = models.CharField(
        max_length=1,
        choices=[
            ("М", "Мужской"),
            ("Ж", "Женский"),
        ],
        verbose_name="Пол",
        **NULLABLE,
    )
    profile_picture = models.ImageField(
        upload_to="profile_pictures/",
        **NULLABLE,
        verbose_name="Фото профиля",
    )
    address = models.CharField(
        max_length=255,
        **NULLABLE_FOR_STRING,
        verbose_name="Адрес",
    )
    role = models.CharField(
        max_length=20,
        choices=UserRole.choices,
        default=UserRole.USER,
        verbose_name="Роль",
    )
    status = models.CharField(
        max_length=10,
        choices=[
            ("active", "Активный"),
            ("inactive", "Неактивный"),
            ("banned", "Заблокирован"),
        ],
        default="active",
        verbose_name="Статус",
    )
    is_active = models.BooleanField(
        default=True,
        verbose_name="Активен",
    )

    # email_verified = models.BooleanField(default=False, verbose_name=_("Email подтверждён"))
    # phone_verified = models.BooleanField(default=False, verbose_name=_("Телефон подтверждён"))
    # telegram_verified = models.BooleanField(default=False, verbose_name=_("Telegram подтверждён"))

    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = []


class Meta:
    verbose_name = "Пользователь"
    verbose_name_plural = "Пользователи"
    ordering = ["id"]


def __str__(self):
    return self.email


def get_full_name(self):
    return f"{self.first_name} {self.last_name}"


def get_short_name(self):
    return self.first_name


def activate(self):
    self.is_active = True
    self.save()


def deactivate(self):
    self.is_active = False
    self.save()

kennel/users/forms.py
from django import forms
from django.core.exceptions import ValidationError
from django.contrib.auth.forms import (
    PasswordChangeForm,
    UserCreationForm,
)

from .models import User
from .validators import (
    PasswordValidator,
    PhoneNumberValidator,
    TelegramUsernameValidator,
)
from config.core.validators.common import (
    DateValidator,
    PhotoValidator,
)


class UserForm(forms.ModelForm):
    """Форма для пользователя."""

    class Meta:
        model = User
        exclude = ("is_active", "status")


class UserRegisterForm(UserCreationForm):
    """Форма регистрации пользователя."""

    class Meta:
        model = User
        fields = ("email",)

    def clean_password2(self):
        """Проверка на совпадение паролей."""
        password1 = self.cleaned_data.get("password1")
        password2 = self.cleaned_data.get("password2")
        PasswordValidator.validate_password(password1)
        if password1 and password2 and password1 != password2:
            raise ValidationError("Пароли не совпадают.")
        return password2

    def clean_email(self):
        """Валидация email для регистрации."""
        email = self.cleaned_data.get("email").strip().lower()
        if User.objects.filter(email=email).exists():
            raise ValidationError(f'Увы, адрес "{email}" уже занят. Попробуйте другой.')
        return email


class UserLoginForm(forms.Form):
    """Форма авторизации пользователя с email"""

    email = forms.EmailField(
        label="Эл. почта",
        # validators=[validate_custom_email],
    )
    password = forms.CharField(
        label="Пароль",
        widget=forms.PasswordInput,
        min_length=8,
    )

    def __init__(self, *args, **kwargs):
        kwargs.pop("request", None)
        super().__init__(*args, **kwargs)

    def clean_password(self):
        """Валидация пароля."""
        password = self.cleaned_data.get("password")
        return PasswordValidator.validate_password(password)

    def clean(self):
        """
        Проверка существует ли пользователь в базе.
        Проверка блокировки доступа к аккаунту.
        """
        email = self.cleaned_data.get("email").strip().lower()
        password = self.cleaned_data.get("password")
        if email and password:
            try:
                user = User.objects.get(email=email)
            except User.DoesNotExist:
                self.add_error("email", ValidationError("Неверный email."))
                return self.cleaned_data
            if not user.check_password(password):
                self.add_error("password", ValidationError("Неверный пароль."))
                return self.cleaned_data
            if not user.is_active:
                raise ValidationError(
                    "Доступ заблокирован, обратитесь к администрации сайта."
                )
            self.user_cache = user
        return self.cleaned_data

    def get_user(self):
        """Возвращает аутентифицированного пользователя из кеша формы.
        Returns:
            User: Объект пользователя, сохранённый после успешной валидации в clean().
        """
        return self.user_cache


class UserUpdateForm(forms.ModelForm):
    """Форма для обновления данных пользователя."""

    class Meta:
        model = User
        fields = (
            "first_name",
            "last_name",
            "email",
            "phone",
            "telegram",
            "birth_date",
            "gender",
            "address",
            "profile_picture",
        )
        widgets = {
            "birth_date": forms.DateInput(
                attrs={"placeholder": "дд.мм.гггг", "class": "form-control"}
            ),
        }

    def clean_phone(self):
        """Валидация номера телефона."""
        phone = self.cleaned_data.get("phone")
        return PhoneNumberValidator.validate_phone(phone)

    def clean_telegram(self):
        """Валидация номера телеграмм."""
        telegram = self.cleaned_data.get("telegram")
        return TelegramUsernameValidator.validate_telegram(telegram)

    def clean_birth_date(self):
        """Валидация даты рождения"""
        birth_date = self.cleaned_data.get("birth_date")
        return DateValidator.age_limit(birth_date, 120, "человека")

    def clean_email(self):
        """Валидация email для обновления."""
        email = self.cleaned_data.get("email").strip().lower()
        user_email = self.instance.email.strip().lower()
        if email != user_email and User.objects.filter(email=email).exists():
            raise ValidationError(f"{email} уже зарегистрирован.")
        return email

    def clean_profile_picture(self):
        """Валидация фото профиля."""
        new_photo = self.cleaned_data.get("profile_picture")
        if not new_photo:
            return
        PhotoValidator.photo_size(new_photo)
        PhotoValidator.photo_extension(new_photo)
        PhotoValidator.delete_old_photo(self.instance, "profile_picture", new_photo)
        return new_photo


class UserPasswordChangeForm(PasswordChangeForm):
    """Форма для смены пароля."""

    def clean_new_password2(self):
        password1 = self.cleaned_data.get("new_password1")
        password2 = self.cleaned_data.get("new_password2")
        PasswordValidator.validate_password(password1)
        if password1 and password2 and password1 != password2:
            raise ValidationError("Пароли не совпадают.")
        return password2

    def save(self, commit=True):
        """
        Сохраняет новый пароль пользователя в БД.
        Обновляет сессию.
        """
        password = self.cleaned_data["new_password1"]
        self.user.set_password(password)
        if commit:
            self.user.save()
        return self.user


class UserEmailExistsForm(forms.Form):
    """Форма для проверки наличия в базе почты."""

    email = forms.EmailField(
        label="Эл. почта",
        widget=forms.EmailInput(
            attrs={"placeholder": "Введите вашу почту", "class": "form-control"}
        ),
    )

    def clean_email(self):
        """Валидация email, проверка на наличие в базе."""
        email = self.cleaned_data.get("email").strip().lower()
        if not User.objects.filter(email=email).exists():
            raise forms.ValidationError(f"Пользователь {email} не найден.")
        return email

kennel/users/views.py
import random
import string
import logging

from django.http import HttpResponse
from django.shortcuts import render
from django.contrib.auth.views import (
    LoginView,
    PasswordChangeView,
    LogoutView,
)
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import (
    FormView,
    CreateView,
    DetailView,
    UpdateView,
)
from django.urls import reverse_lazy

from config.core.mixins import HtmxRedirectMixin
from .models import User
from .forms import (
    UserRegisterForm,
    UserLoginForm,
    UserUpdateForm,
    UserPasswordChangeForm,
    UserEmailExistsForm,
)
from .services import (
    send_new_password,
    send_register_email,
)

logger_auth = logging.getLogger("users")


class UserRegisterViews(CreateView):
    """
    Регистрация нового пользователя.
    Сохраняет пользователя, если форма валидна, и перенаправляет на страницу профиля.
    """

    model = User
    form_class = UserRegisterForm
    template_name = "users/register.html"
    success_url = reverse_lazy("users:login")
    extra_context = {
        "title": "Регистрация пользователя",
    }

    def form_valid(self, form):
        send_register_email(form.clean_email())
        return super().form_valid(form)


class UserLoginView(LoginView):
    """
    Вход пользователя.
    Аутентифицирует пользователя и перенаправляет в профиль при успешном входе.
    """

    form_class = UserLoginForm
    template_name = "users/login.html"
    redirect_authenticated_user = True  # Перенаправляет авторизованного пользователя. Что бы не регистрировался заново.
    extra_context = {
        "title": "Авторизация пользователя",
    }

    # noinspection PyTypeChecker
    def form_valid(self, form):
        logger_auth.info(
            f"Пользователь {form.cleaned_data.get('email')} вошёл в систему."
        )
        return super().form_valid(form)


class UserProfileView(LoginRequiredMixin, DetailView):
    """
    Профиль пользователя.
    Отображает страницу профиля для авторизованных пользователей.
    """

    model = User
    template_name = "users/profile.html"
    extra_context = {
        "title": "Ваш профиль",
    }

    def get_object(self, queryset=None):
        return self.request.user


class UserUpdateView(LoginRequiredMixin, HtmxRedirectMixin, UpdateView):
    """
    Обновление данных пользователя.
    Позволяет обновить профиль, включая фото.
    Удаляет старую фотографию при загрузке новой.
    """

    model = User
    form_class = UserUpdateForm
    template_name = "users/user_includes/update.html"
    success_url = reverse_lazy("users:profile")
    extra_context = {
        "title": "Изменение профиля",
    }

    def get_object(self, queryset=None):
        return self.request.user

    def form_valid(self, form):
        form.save()
        logger_auth.info(
            f"Пользователь {form.cleaned_data.get("email")} изменил свои данные."
        )
        return super().form_valid(form)


class UserPasswordChangeView(LoginRequiredMixin, HtmxRedirectMixin, PasswordChangeView):
    """
    Смена пароля пользователя.
    Обновляет пароль и сессию при успешной валидации формы.
    """

    form_class = UserPasswordChangeForm
    template_name = "users/user_includes/password-change.html"
    success_url = reverse_lazy("users:login")
    extra_context = {
        "title": "Смена пароля",
    }

    def form_valid(self, form):
        form.save()
        logger_auth.info(f"Пользователь {self.request.user.email} изменил пароль.")
        return super().form_valid(form)


class UserLogoutView(LogoutView):
    """
    Выход пользователя.
    Завершающий сеанс и перенаправление на главную страницу.
    """

    def dispatch(self, request, *args, **kwargs):
        user = request.user
        response = super().dispatch(request, *args, **kwargs)
        logger_auth.info(f"Пользователь {user.email} вышел из системы.")
        return response


def reset_password_success(request):
    return render(
        request,
        "users/reset-password-success.html",
    )


class UserResetPasswordView(FormView):
    """
    Восстановление пароля.
    Перенаправление на страницу с подтверждением.
    """

    form_class = UserEmailExistsForm
    template_name = "users/reset-password.html"
    success_url = reverse_lazy("users:reset-password-success")
    extra_context = {
        "title": "Восстановление пароля",
    }

    def form_valid(self, form):
        email = form.cleaned_data["email"]
        user = User.objects.get(email=email)
        new_password = "".join(
            random.sample((string.ascii_letters + string.digits), 12)
        )
        user.set_password(new_password)
        user.save()
        send_new_password(user.email, new_password)
        logger_auth.info(f"Пользователь {email} восстановил пароль.")
        if "HX-Request" in self.request.headers:
            response = HttpResponse()
            response["HX-Redirect"] = self.get_success_url()
            return response
        return super().form_valid(form)

kennel/users/templates/users/login.html
{% extends 'base.html' %}
{% block content %}
  <div id="login-form__resset-password"
       class="form-container"
  >
    <form class="form"
          method="post"
    >
      <div class=" form__title">
        Войдите в свою учетную запись
      </div>
      {% csrf_token %}
      <div class="form__group">
        {% for field in form %}
          <div class="form__group-item">
            {% if field.name == "password" %}
              <div class="login-form__reset-password-block">
                <label class="form__group-label">
                  {{ field.label }}:{% if field.field.required %} *{% endif %}
                </label>
                <a>
                  <small class="login-form__reset-password-text"
                         hx-get="{% url 'users:reset-password' %}"
                         hx-target="#login-form__resset-password"
                         hx-swap="innerHTML"
                  >
                    Забыли?
                  </small>
                </a>
              </div>
            {% else %}
              <label class="form__group-label">
                {{ field.label }}:{% if field.field.required %} *{% endif %}
              </label>
            {% endif %}
            <div class="form__group-field">
              {{ field }}
            </div>
            {% if field.errors %}
              <div class="form__group-error">
                {{ field.errors }}
              </div>
            {% elif field.name == "password" and  form.non_field_errors %}
              {% for error in form.non_field_errors %}
                <div class="form__group-error">
                  <p>{{ error }}</p>
                </div>
              {% endfor %}
            {% endif %}
          </div>
        {% endfor %}
        <button class="btn form__btn" type="submit">
          Войти
        </button>
      </div>
    </form>
  </div>
{% endblock %}

kennel/users/templates/users/profile.html
{% extends 'base.html' %}
{% load user_tags %}

{% block content %}
  {% include "includes/title-top.html" %}
  <section class="user-profile">
    <div class="container">
      <div class="user-profile__wrapper">
        <div class="user-profile__item">
          <img class="user-profile__img" src="{{ user.profile_picture|user_media }}" alt="user photo">
        </div>
        <div id="user-update"
             class="user-profile__item user-profile__item-info"
        >
          <div class="user-profile__group-info">
            <div class="user-profile__text">
              <p class="user-profile__text-inner">Имя:</p>
              {{ user.first_name|default:"Не указано" }}
            </div>
            <div class="user-profile__text">
              <p class="user-profile__text-inner">Фамилия:</p>
              {{ user.last_name|default:"Не указано" }}
            </div>
            <div class="user-profile__text">
              <p class="user-profile__text-inner">Эл.почта:</p>
              {{ user.email|default:"Не указано" }}
            </div>
            <div class="user-profile__text">
              <p class="user-profile__text-inner">Телефон:</p>
              {{ user.phone|default:"Не указано" }}
            </div>
            <div class="user-profile__text">
              <p class="user-profile__text-inner">Телеграм:</p>
              {{ user.telegram|default:"Не указано" }}
            </div>
            <div class="user-profile__text">
              <p class="user-profile__text-inner">Дата рождения:</p>
              {{ user.birth_date|default:"Не указано" }}
            </div>
            <div class="user-profile__text">
              <p class="user-profile__text-inner">Пол:</p>
              {{ user.get_gender_display|default:"Не указано" }}
            </div>
            <div class="user-profile__text">
              <p class="user-profile__text-inner">Адрес:</p>
              {{ user.address|default:"Не указано" }}
            </div>
          </div>
          <div class="user-profile__group-links">
            <a class="user-link"
               hx-get="{% url 'users:update' %}"
               hx-target="#user-update"
               hx-swap="innerHTML"
            >
              <small class="user-link__text">
                Изменить данные
              </small>
            </a>

            <a class="user-link"
               hx-get="{% url 'users:password-change' %}"
               hx-target="#user-update"
               hx-swap="innerHTML"
            >
              <small class="user-link__text">
                Сменить пароль
              </small>
            </a>
          </div>
        </div>
      </div>
    </div>
  </section>
{% endblock %}

kennel/users/templates/users/register.html
{% extends 'base.html' %}
{% block content %}
  <form class="form"
        method="post"
        enctype="multipart/form-data"
  >
    <div class="form__title">
      Регистрации пользователя
    </div>
    {% csrf_token %}
    <div class="form__group">
      {% for field in form %}
        <div class="form__group-item">
            <label class="form__group-label">
              {{ field.label }}:{% if field.field.required %} *{% endif %}
            </label>
          <div class="form__group-field">
              {{ field }}
          </div>
          {% if field.errors %}
            <div class="form__group-error">
              {{ field.errors }}
            </div>
          {% endif %}
        </div>
      {% endfor %}
      <button class="btn form__btn" type="submit">
        Добавить
      </button>
    </div>
  </form>
{% endblock %}

kennel/users/templates/users/reset-password-success.html
{% extends 'base.html' %}

{% block content %}
<section class="password-reset-success-page">
    <div class="password-reset-success-box">
        <h1 class="password-reset-success-title">Пароль восстановлен!</h1>
        <p class="password-reset-success-text">Мы отправили письмо с новым паролем на указанный email.</p>
        <p class="password-reset-success-text">Проверьте почту и войдите в аккаунт, используя новый пароль.<br>
          <span style="color: #ca5555">
            Возможно придется проверить еще и спам.
          </span>
        </p>
        <a href="{% url 'users:login' %}" class="password-reset-success-button">Вернуться ко входу</a>
    </div>
</section>
{% endblock %}

kennel/users/templates/users/reset-password.html
<div class="form-container">
  <form class="form"
        method="post"
        hx-post="{% url 'users:reset-password' %}"
        hx-swap="outerHTML"
  >
    <div class=" form__title">
      Восстановление пароля
    </div>
    {% csrf_token %}
    <div class="form__group">
      {% for field in form %}
        <div class="form__group-item">
          <label class="form__group-label">
            {{ field.label }}:{% if field.field.required %} *{% endif %}
          </label>
          <div class="form__group-field">
            {{ field }}
          </div>
          {% if field.errors %}
            <div class="form__group-error">
              {{ field.errors }}
            </div>
          {% endif %}
        </div>
      {% endfor %}
      {% if message %}
        <div class="alert alert-success">{{ message }}</div>
      {% endif %}
      <button class="btn form__btn" type="submit">
        Отправить
      </button>
    </div>
  </form>
</div>